force-app/main/default/objects/Record_Sync__c/Record_Sync__c.object-meta.xml
<CustomObject>
    <label>Record Sync</label>
    <nameField>
        <displayFormat>RS-{00000}</displayFormat>
        <label>Record Sync Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Records Sync</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Record_Sync__c/fields/Record_Sync_Run__c.field-meta.xml
<CustomField>
    <fullName>Record_Sync_Run__c</fullName>
    <label>Record Sync Run</label>
    <referenceTo>Record_Sync_Run__c</referenceTo>
    <relationshipLabel>Records Sync</relationshipLabel>
    <relationshipName>Records_Sync</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Record_Sync__c/fields/Source_Record__c.field-meta.xml
<CustomField>
    <fullName>Source_Record__c</fullName>
    <label>Source Record</label>
    <length>18</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Record_Sync__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Pending</fullName>
                <default>true</default>
                <label>Pending</label>
            </value>
            <value>
                <fullName>Failed</fullName>
            </value>
            <value>
                <fullName>Updated</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Record_Sync__c/fields/Target_Record__c.field-meta.xml
<CustomField>
    <fullName>Target_Record__c</fullName>
    <label>Target Record</label>
    <length>18</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Record_Sync_Run__c/Record_Sync_Run__c.object-meta.xml
<CustomObject>
    <label>Record Sync Run</label>
    <nameField>
        <displayFormat>RSR-{00000}</displayFormat>
        <label>Record Sync Run Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Record Sync Runs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Record_Sync_Run__c/fields/From__c.field-meta.xml
<CustomField>
    <fullName>From__c</fullName>
    <label>From</label>
    <required>true</required>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Record_Sync_Run__c/fields/Minimum_Score__c.field-meta.xml
<CustomField>
    <fullName>Minimum_Score__c</fullName>
    <label>Minimum Score</label>
    <precision>3</precision>
    <required>true</required>
    <scale>0</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/objects/Record_Sync_Run__c/fields/Search_Fields__c.field-meta.xml
<CustomField>
    <fullName>Search_Fields__c</fullName>
    <label>Search Fields</label>
    <length>131072</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Record_Sync_Run__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Search In Progress</fullName>
                <default>true</default>
                <label>Search In Progress</label>
            </value>
            <value>
                <fullName>Failed</fullName>
            </value>
            <value>
                <fullName>Ready to Sync</fullName>
            </value>
            <value>
                <fullName>Sync In Progress</fullName>
            </value>
            <value>
                <fullName>Completed</fullName>
            </value>
            <value>
                <fullName>No Records Found</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Record_Sync_Run__c/fields/Update_Fields__c.field-meta.xml
<CustomField>
    <fullName>Update_Fields__c</fullName>
    <label>Update Fields</label>
    <length>131072</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/classes/BatchUpdateDuplicatesInvocationTest.cls
@isTest
public class BatchUpdateDuplicatesInvocationTest {

    @isTest
    static void testBatchExecuteMethod()
    {
      Record_Sync_Run__c rsr = new Record_Sync_Run__c();
     
      rsr.Status__c = 'Ready to Sync';
      rsr.Minimum_Score__c = 60;
      rsr.From__c = Date.today().addDays(-2);
      rsr.Search_Fields__c = 'Name,AccountSource,AnnualRevenue,Type';
      rsr.Update_Fields__c = 'Name,AccountSource,AnnualRevenue,Type';
           
      insert rsr; 
        
      Id recordSyncRunId = [SELECT id FROM Record_Sync_Run__c LIMIT 1].id;
        
            Record_Sync__c recordSync = new Record_Sync__c(
            Target_Record__c= '0016300001LHlsPAAT', 
            Source_Record__c= '0016300001LKwJLAA1', 
            Status__c='Pending',
            Record_Sync_Run__c = recordSyncRunId
                
           
        );
      insert recordSync;
        
      FunctionsInvokeMockInner mock = new FunctionsInvokeMockInner();
  
      Test.setMock(functions.FunctionInvokeMock.class, mock);
   
      functions.Function updateDuplicatesFx = functions.Function.get(
      	'record_sync_app.updateduplicatedrecords'
      );
   
        
      try {
          Test.startTest();
          BatchUpdateDuplicatesInvocation batchTest = new BatchUpdateDuplicatesInvocation(rsr,updateDuplicatesFx);
          Id jobid = Database.executeBatch(batchTest,5);
          Test.stopTest();
          
          if(!mock.throwError){
              Record_Sync_Run__c run = [Select Status__c from Record_Sync_Run__c where Id =:rsr.Id]; 
              run.Status__c = 'Completed';
             
              update run;
          }
         	
          List<Record_Sync_Run__c> acc = new List<Record_Sync_Run__c>(); 
     	  acc = [Select Status__c from Record_Sync_Run__c where Status__c = 'Completed'];
       
     	  System.assertEquals(1, acc.size());
         
        } catch (Exception e) {
          // THEN
          System.assert(e instanceof CalloutException, 'Expected CalloutException');
          System.assertEquals(mock.error, e.getMessage());
      }
    }
    
    public class FunctionsInvokeMockInner implements functions.FunctionInvokeMock {
    public String response = 'Success!';
    public String error = 'Function returned an error!';
    public Boolean throwError = false;
    private String invocationId = '000000000000000';

    public functions.FunctionInvocation respond(String functionName, String payload) {
          if (throwError) {
            return functions.MockFunctionInvocationFactory.createErrorResponse(
              invocationId,
              functions.FunctionErrorType.FUNCTION_EXCEPTION,
              error
            );
          }
    
          return functions.MockFunctionInvocationFactory.createSuccessResponse(
            invocationId,
            response
          );
        }
    }
    
}