force-app/main/default/objects/Record_Sync__c/Record_Sync__c.object-meta.xml
<CustomObject>
    <label>Record Sync</label>
    <nameField>
        <displayFormat>RS-{00000}</displayFormat>
        <label>Record Sync Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Records Sync</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Record_Sync__c/fields/Record_Sync_Run__c.field-meta.xml
<CustomField>
    <fullName>Record_Sync_Run__c</fullName>
    <label>Record Sync Run</label>
    <referenceTo>Record_Sync_Run__c</referenceTo>
    <relationshipLabel>Records Sync</relationshipLabel>
    <relationshipName>Records_Sync</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Record_Sync__c/fields/Source_Record__c.field-meta.xml
<CustomField>
    <fullName>Source_Record__c</fullName>
    <label>Source Record</label>
    <length>18</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Record_Sync__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Pending</fullName>
                <default>true</default>
                <label>Pending</label>
            </value>
            <value>
                <fullName>Failed</fullName>
            </value>
            <value>
                <fullName>Updated</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Record_Sync__c/fields/Target_Record__c.field-meta.xml
<CustomField>
    <fullName>Target_Record__c</fullName>
    <label>Target Record</label>
    <length>18</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Record_Sync_Run__c/Record_Sync_Run__c.object-meta.xml
<CustomObject>
    <label>Record Sync Run</label>
    <nameField>
        <displayFormat>RSR-{00000}</displayFormat>
        <label>Record Sync Run Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Record Sync Runs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Record_Sync_Run__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Search In Progress</fullName>
                <default>true</default>
                <label>Search In Progress</label>
            </value>
            <value>
                <fullName>Failed</fullName>
            </value>
            <value>
                <fullName>Ready to Sync</fullName>
            </value>
            <value>
                <fullName>Sync In Progress</fullName>
            </value>
            <value>
                <fullName>Completed</fullName>
            </value>
            <value>
                <fullName>No Records Found</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Record_Sync_Run__c/fields/Update_Fields__c.field-meta.xml
<CustomField>
    <fullName>Update_Fields__c</fullName>
    <label>Update Fields</label>
    <length>131072</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/classes/BatchUpdateDuplicatesInvocation.cls
/**
 * @description Apex Class to run the update duplicates function in batches.
 */
public with sharing class BatchUpdateDuplicatesInvocation implements Database.Batchable<sObject> {
  private Record_Sync_Run__c recordSyncRun;
  private functions.Function updateDuplicatesFunction;

  public BatchUpdateDuplicatesInvocation(
    Record_Sync_Run__c rsr,
    functions.Function updateDuplicatesFunc
  ) {
    this.recordSyncRun = rsr;
    this.updateDuplicatesFunction = updateDuplicatesFunc;
  }
  /**
   * @description get the query locator.
   * @param  bc BatchableContext Context
   * @return query locator
   */
  public Database.querylocator start(Database.BatchableContext bc) {
    Id recordSyncRunId = this.recordSyncRun.Id;
    return Database.getQueryLocator(
      'SELECT Id, Target_Record__c, Source_Record__c, Status__c FROM Record_Sync__c WHERE Record_Sync_Run__c = :recordSyncRunId'
    );
  }
  /**
   * @description execute the update function in batches.
   * @param  bc BatchableContext Context
   * @param records list of records to be processed
   */
  public void execute(Database.BatchableContext bc, List<sObject> records) {
    FunctionUpdateInput functionInput = new FunctionUpdateInput();
    functionInput.recordSyncIds = (new Map<Id, SObject>(records)).keySet();
    functionInput.fields = this.recordSyncRun.Update_Fields__c;
    functions.FunctionInvocation invocation = this.updateDuplicatesFunction.invoke(
      JSON.serialize(functionInput)
    );
    // Check if there is any error during the invocation
    if (invocation.getStatus() == functions.FunctionInvocationStatus.ERROR) {
      throw new CalloutException(
        (invocation.getError() != null
          ? invocation.getError().getMessage()
          : 'UNKNOWN')
      );
    }
  }
  /**
   * @description Update record sync run to completed when all batches are done.
   * @param  bc BatchableContext Context
   */
  public void finish(Database.BatchableContext bc) {
    this.recordSyncRun.Status__c = 'Completed';
    new Safely().doUpdate(this.recordSyncRun);
  }

  public class FunctionUpdateInput {
    public Set<Id> recordSyncIds;
    public String fields;
  }
}