force-app/main/default/objects/Record_Sync__c/Record_Sync__c.object-meta.xml
<CustomObject>
    <label>Record Sync</label>
    <nameField>
        <displayFormat>RS-{00000}</displayFormat>
        <label>Record Sync Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Records Sync</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Record_Sync__c/fields/Record_Sync_Run__c.field-meta.xml
<CustomField>
    <fullName>Record_Sync_Run__c</fullName>
    <label>Record Sync Run</label>
    <referenceTo>Record_Sync_Run__c</referenceTo>
    <relationshipLabel>Records Sync</relationshipLabel>
    <relationshipName>Records_Sync</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Record_Sync__c/fields/Source_Record__c.field-meta.xml
<CustomField>
    <fullName>Source_Record__c</fullName>
    <label>Source Record</label>
    <length>18</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Record_Sync__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Pending</fullName>
                <default>true</default>
                <label>Pending</label>
            </value>
            <value>
                <fullName>Failed</fullName>
            </value>
            <value>
                <fullName>Updated</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Record_Sync__c/fields/Target_Record__c.field-meta.xml
<CustomField>
    <fullName>Target_Record__c</fullName>
    <label>Target Record</label>
    <length>18</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Record_Sync_Run__c/Record_Sync_Run__c.object-meta.xml
<CustomObject>
    <label>Record Sync Run</label>
    <nameField>
        <displayFormat>RSR-{00000}</displayFormat>
        <label>Record Sync Run Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Record Sync Runs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Record_Sync_Run__c/fields/From__c.field-meta.xml
<CustomField>
    <fullName>From__c</fullName>
    <label>From</label>
    <required>true</required>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Record_Sync_Run__c/fields/Minimum_Score__c.field-meta.xml
<CustomField>
    <fullName>Minimum_Score__c</fullName>
    <label>Minimum Score</label>
    <precision>3</precision>
    <required>true</required>
    <scale>0</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/objects/Record_Sync_Run__c/fields/Search_Fields__c.field-meta.xml
<CustomField>
    <fullName>Search_Fields__c</fullName>
    <label>Search Fields</label>
    <length>131072</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Record_Sync_Run__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Search In Progress</fullName>
                <default>true</default>
                <label>Search In Progress</label>
            </value>
            <value>
                <fullName>Failed</fullName>
            </value>
            <value>
                <fullName>Ready to Sync</fullName>
            </value>
            <value>
                <fullName>Sync In Progress</fullName>
            </value>
            <value>
                <fullName>Completed</fullName>
            </value>
            <value>
                <fullName>No Records Found</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Record_Sync_Run__c/fields/Update_Fields__c.field-meta.xml
<CustomField>
    <fullName>Update_Fields__c</fullName>
    <label>Update Fields</label>
    <length>131072</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/classes/RecordSyncRunControllerTest.cls
@isTest
public class RecordSyncRunControllerTest {

    @isTest
    static void getRecordFields(){
        List<String> recordFields = new List<String>();
		RecordSyncRunController.FieldListWrapper fieldListWrapper = RecordSyncRunController.getRecordFields();
		List<RecordSyncRunController.FieldWrapper> fieldsWrapper = fieldListWrapper.searchFields;
		for(RecordSyncRunController.FieldWrapper fieldWrapper: fieldsWrapper ){
		    recordFields.add(fieldWrapper.value);
		}
        
		Boolean name = recordFields.contains('Name');
		System.assertEquals(true, name);
        
        Boolean parentId = recordFields.contains('ParentId');
        System.assertEquals(false,parentId);
        
    }
	
    @isTest
        static void createSyncRun(){
 		String searchFields = 'name,BillingCity' ;
        String updateFields = 'name' ;
        Date fromDate = Date.newInstance(2022,1,1) ;
        Integer minimumScore = 1;
        Test.startTest();
        	String runId = RecordSyncRunController.createSyncRun(searchFields,updateFields,fromDate,minimumScore);
        	Id recordSyncRunId = [SELECT id FROM Record_Sync_Run__c LIMIT 1].id;
        Test.stopTest();
		System.assertEquals(String.valueOf(recordSyncRunId), runId);
    }
    
    @isTest
    static void updateDuplicatesAction(){
        FunctionsInvokeMockInner mock = new FunctionsInvokeMockInner();
    	Test.setMock(functions.FunctionInvokeMock.class, mock);
        
        List<Record_Sync_Run__c> listRecordSyncRun = new List<Record_Sync_Run__c>();
        String searchFields = 'name,BillingCity' ;
        String updateFields = 'name' ;
        Date fromDate = Date.newInstance(2022,1,1) ;
        Integer minimumScore = 1;
        
        Record_Sync_Run__c recordSyncRun = new Record_Sync_Run__c(
        Search_Fields__c = searchFields,
        Update_Fields__c = updateFields,
        From__c = fromDate,
        Minimum_Score__c = minimumScore,
        Status__c = 'Search In Progress');
        
        listRecordSyncRun.add(recordSyncRun);
        insert recordSyncRun;

        Test.startTest();

        Id recordSyncRunId = [SELECT id FROM Record_Sync_Run__c LIMIT 1].id;
        
            Record_Sync__c recordSync = new Record_Sync__c(
            Target_Record__c= '0016300001LHlsPAAT', 
            Source_Record__c= '0016300001LKwJLAA1', 
            Status__c='Pending',
            Record_Sync_Run__c = recordSyncRunId
        );
        insert recordSync;
        List<String> result = RecordSyncRunController.updateDuplicatesAction(listRecordSyncRun);
        List<AsyncApexJob> batch = [SELECT id FROM AsyncApexJob WHERE Id=:result.get(0)];
		Test.stopTest();
		System.assertEquals(1,batch.size()); 
    }
    
    public class FunctionsInvokeMockInner implements functions.FunctionInvokeMock {
    public String response = 'Success!';
    public String error = 'Function returned an error!';
    public Boolean throwError = false;
    private String invocationId = '000000000000000';

    public functions.FunctionInvocation respond(
      String functionName,
      String payload
    ) {
      if (throwError) {
        return functions.MockFunctionInvocationFactory.createErrorResponse(
          invocationId,
          functions.FunctionErrorType.FUNCTION_EXCEPTION,
          error
        );
      }

      return functions.MockFunctionInvocationFactory.createSuccessResponse(
        invocationId,
        response
      );
    }
  }
}