force-app/main/default/objects/Record_Sync_Run__c/Record_Sync_Run__c.object-meta.xml
<CustomObject>
    <label>Record Sync Run</label>
    <nameField>
        <displayFormat>RSR-{00000}</displayFormat>
        <label>Record Sync Run Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Record Sync Runs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Record_Sync_Run__c/fields/Duplicated_Records__c.field-meta.xml
<CustomField>
    <fullName>Duplicated_Records__c</fullName>
    <label>Duplicated Records</label>
    <summaryForeignKey>Record_Sync__c.Record_Sync_Run__c</summaryForeignKey>
    <summaryOperation>count</summaryOperation>
    <type>Summary</type>
</CustomField>

force-app/main/default/objects/Record_Sync_Run__c/fields/From__c.field-meta.xml
<CustomField>
    <fullName>From__c</fullName>
    <label>From</label>
    <required>true</required>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Record_Sync_Run__c/fields/Minimum_Score__c.field-meta.xml
<CustomField>
    <fullName>Minimum_Score__c</fullName>
    <label>Minimum Score</label>
    <precision>3</precision>
    <required>true</required>
    <scale>0</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/objects/Record_Sync_Run__c/fields/Search_Fields__c.field-meta.xml
<CustomField>
    <fullName>Search_Fields__c</fullName>
    <label>Search Fields</label>
    <length>131072</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Record_Sync_Run__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Search In Progress</fullName>
                <default>true</default>
                <label>Search In Progress</label>
            </value>
            <value>
                <fullName>Failed</fullName>
            </value>
            <value>
                <fullName>Ready to Sync</fullName>
            </value>
            <value>
                <fullName>Sync In Progress</fullName>
            </value>
            <value>
                <fullName>Completed</fullName>
            </value>
            <value>
                <fullName>No Records Found</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/BatchFindDuplicatesInvocation.cls
/**
 * @description Apex Class to run the search of record sync records in batches.
 */
public with sharing class BatchFindDuplicatesInvocation implements Database.Batchable<sObject> {
  private Record_Sync_Run__c recordSyncRun;
  private functions.Function findDuplicatesFunction;

  public BatchFindDuplicatesInvocation(
    Record_Sync_Run__c rsr,
    functions.Function findDuplicatesFunc
  ) {
    this.recordSyncRun = rsr;
    this.findDuplicatesFunction = findDuplicatesFunc;
  }
  /**
   * @description get the query locator.
   * @param  bc BatchableContext Context
   * @return query locator
   */
  public Database.querylocator start(Database.BatchableContext bc) {
    @SuppressWarnings('PMD.UnusedLocalVariable')
    Date fromDate = this.recordSyncRun.From__c;
    // TODO: make this generic to work with any object.
    return Database.getQueryLocator(
      'SELECT Id,' +
      this.recordSyncRun.Search_Fields__c +
      ' FROM Account WHERE LastModifiedDate >= :fromDate ORDER BY NAME LIMIT 10000'
    );
  }

  /**
   * @description execute find function in batches
   * @param  bc BatchableContext Context
   * @param records list of records to be processed
   */
  public void execute(Database.BatchableContext bc, List<sObject> records) {
    FunctionFindInput functionInput = new FunctionFindInput();
    functionInput.recordSyncRunId = this.recordSyncRun.Id;
    functionInput.searchFields = this.recordSyncRun.Search_Fields__c;
    functionInput.minimumScore = this.recordSyncRun.Minimum_Score__c > 0
      ? this.recordSyncRun.Minimum_Score__c / 100
      : 0;
    functionInput.targetRecordIds = (new Map<String, SObject>(records))
      .keySet();
    functions.FunctionInvocation invocation = this.findDuplicatesFunction.invoke(
      JSON.serialize(functionInput)
    );
    if (invocation.getStatus() == functions.FunctionInvocationStatus.ERROR) {
      throw new CalloutException(
        (invocation.getError() != null
          ? invocation.getError().getMessage()
          : 'UNKNOWN')
      );
    }
  }
  /**
   * @description Update record merge run to completed when all batches are done.
   * @param  bc BatchableContext Context
   */
  public void finish(Database.BatchableContext bc) {
    String recordSyncRunId = this.recordSyncRun.Id;
    Record_Sync_Run__c rsr = [
      SELECT Id, Duplicated_Records__c
      FROM Record_Sync_Run__c
      WHERE Id = :recordSyncRunId
      LIMIT 1
    ];
    if (rsr.Duplicated_Records__c > 0) {
      this.recordSyncRun.Status__c = 'Ready to Sync';
    } else {
      this.recordSyncRun.Status__c = 'No Records Found';
    }
    new Safely().doUpdate(this.recordSyncRun);
  }

  /**
   * @description Function Find Input
   */
  public class FunctionFindInput {
    public Id recordSyncRunId;
    public String searchFields;
    public Decimal minimumScore;
    public Set<String> targetRecordIds;
  }
}