force-app/main/default/objects/Record_Sync_Run__c/Record_Sync_Run__c.object-meta.xml
<CustomObject>
    <label>Record Sync Run</label>
    <nameField>
        <displayFormat>RSR-{00000}</displayFormat>
        <label>Record Sync Run Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Record Sync Runs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Record_Sync_Run__c/fields/From__c.field-meta.xml
<CustomField>
    <fullName>From__c</fullName>
    <label>From</label>
    <required>true</required>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Record_Sync_Run__c/fields/Minimum_Score__c.field-meta.xml
<CustomField>
    <fullName>Minimum_Score__c</fullName>
    <label>Minimum Score</label>
    <precision>3</precision>
    <required>true</required>
    <scale>0</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/objects/Record_Sync_Run__c/fields/Search_Fields__c.field-meta.xml
<CustomField>
    <fullName>Search_Fields__c</fullName>
    <label>Search Fields</label>
    <length>131072</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Record_Sync_Run__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Search In Progress</fullName>
                <default>true</default>
                <label>Search In Progress</label>
            </value>
            <value>
                <fullName>Failed</fullName>
            </value>
            <value>
                <fullName>Ready to Sync</fullName>
            </value>
            <value>
                <fullName>Sync In Progress</fullName>
            </value>
            <value>
                <fullName>Completed</fullName>
            </value>
            <value>
                <fullName>No Records Found</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/BatchFindDuplicatesInvocationTest.cls
@isTest
public class BatchFindDuplicatesInvocationTest {

    @isTest
    static void testBatchExecuteMethod()
   {
     
     Record_Sync_Run__c rsr = new Record_Sync_Run__c();
     
     rsr.Status__c = 'Search In Progress';
     rsr.Minimum_Score__c = 60;
     rsr.From__c = Date.today().addDays(-2);
     rsr.Search_Fields__c = 'Name,AccountSource,AnnualRevenue,Type';
       
     insert rsr; 
           
     Account a = new Account();
     a.Name = 'John Smith';
     a.AccountSource = 'Web';
     a.AnnualRevenue = 100000;
     a.Type = 'Personal';
     
     insert a;
       
     Account b = new Account();
     b.Name = 'Joh Smith';
     b.AccountSource = 'Web';
     b.AnnualRevenue = 100000;
     b.Type = 'Personal';

     insert b;
            
	 FunctionsInvokeMockInner mock = new FunctionsInvokeMockInner();
     //mock.throwError = true;
     Test.setMock(functions.FunctionInvokeMock.class, mock);
   
     functions.Function findDuplicatesFx = functions.Function.get(
     	'record_sync_app.findduplicatedrecords'
     );
    
     try {
          Test.startTest();
          BatchFindDuplicatesInvocation batchTest = new BatchFindDuplicatesInvocation(rsr,findDuplicatesFx);
          Id jobid = Database.executeBatch(batchTest,5);
          Test.stopTest();
          
          if(!mock.throwError){
              Record_Sync_Run__c run = [Select Status__c from Record_Sync_Run__c where Id =:rsr.Id]; 
              run.Status__c = 'Ready to Sync';
             
              update run;
          }
         	
          List<Record_Sync_Run__c> acc = new List<Record_Sync_Run__c>(); 
     	  acc = [Select Status__c from Record_Sync_Run__c where Status__c = 'Ready to Sync'];
       
     	  System.assertEquals(1, acc.size());
         
        } catch (Exception e) {
          // THEN
          System.assert(e instanceof CalloutException, 'Expected CalloutException');
          System.assertEquals(mock.error, e.getMessage());
      }
     
    }
    
    public class FunctionsInvokeMockInner implements functions.FunctionInvokeMock {
    public String response = 'Success!';
    public String error = 'Function returned an error!';
    public Boolean throwError = false;
    private String invocationId = '000000000000000';

    public functions.FunctionInvocation respond(
      String functionName,
      String payload
    ) {
          if (throwError) {
            return functions.MockFunctionInvocationFactory.createErrorResponse(
              invocationId,
              functions.FunctionErrorType.FUNCTION_EXCEPTION,
              error
            );
          }
    
          return functions.MockFunctionInvocationFactory.createSuccessResponse(
            invocationId,
            response
          );
        }
    }
        
}